// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NativeOpenDialog() {
  return window['go']['main']['App']['NativeOpenDialog']();
}

export function NativePickDirectory() {
  return window['go']['main']['App']['NativePickDirectory']();
}

export function NativeReadFile(arg1) {
  return window['go']['main']['App']['NativeReadFile'](arg1);
}

export function NativeSaveDialog(arg1, arg2) {
  return window['go']['main']['App']['NativeSaveDialog'](arg1, arg2);
}

export function NativeWriteFile(arg1, arg2) {
  return window['go']['main']['App']['NativeWriteFile'](arg1, arg2);
}
