// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NativeOpenDialog():Promise<string>;

export function NativePickDirectory():Promise<string>;

export function NativeReadFile(arg1:string):Promise<string>;

export function NativeSaveDialog(arg1:string,arg2:string):Promise<string>;

export function NativeWriteFile(arg1:string,arg2:string):Promise<void>;
